version: '2'

volumes:
  postgres_data: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../backups:/backups
    environment:
      - POSTGRES_USER=user
    ports:
      - "5432:5432"
    ulimits:
        nproc: 65535
        nofile:
            soft: 20000
            hard: 40000
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=user
      - USE_DOCKER=yes
    volumes:
      - .:/app
      - ../shared:/app/shared
    ports:
      - "8003:8000"
    links:
      - postgres
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
